{...}: {
  programs.zed-editor = {
    enable = true;
    installRemoteServer = true;
    extensions = [
      "autocorrect"
      "cargo-appraiser"
      "cargo-tom"
      "catppuccin"
      "catppuccin-icons"
      "codebook"
      "color-highlight"
      "comment"
      "crates-lsp"
      "csv"
      "discord-presence"
      "env"
      "emoji-completions"
      "fish"
      "github-actions"
      "gitignore-templates"
      "html-snippets"
      "http"
      "hyprlang"
      "ini"
      "json5"
      "jsonl"
      "latex"
      "lean4"
      "live-server"
      "log"
      "make"
      "markdown-oxide"
      "nix"
      "pest"
      "python-refactoring"
      "python-requirements"
      "python-snippets"
      "rainbow-csv"
      "rust-snippets"
      "ssh-config"
      "strace"
      "toml"
      "unicode"
      "xml"
    ];
  };
}
